import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Film } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { MagnifyingGlassIcon } from "@radix-ui/react-icons";
import Sidebar from "@/components/sidebar";
import { Input } from "@/components/ui/input";

import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie Gabar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  async function search(formData: FormData) {
    "use server";
    redirect(`/search?q=${formData.get("q")}`);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <header className="flex justify-between p-4">
          <Link
            href="/"
            className="text-center flex justify-center items-center gap-2"
          >
            <Film />
            <h1 className="text-2xl font-bold">Movie World</h1>
          </Link>
          <form action={search} className="flex gap-1">
            <Input placeholder="Search movies" name="q" />
            <Button type="submit">
              <MagnifyingGlassIcon />
            </Button>
          </form>
        </header>
        <div className="flex ">
          <div className="flex">
            <Sidebar />
          </div>
          <main className="w-full border flex-col p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
